---
title: "Technical Setup"
output: html_document
---



### As I spend a lot of time on my computer and especially in the terminal, I wanted to create a list of tools & technologies I use on a day-to-day basis. This list is both for me, to create a documentation when I need to setup a new enviroment, and for other people to get some inspiration.

#### I am mainly working with MacOS and Linux Ubuntu. All the tools presented in the following list are available for both systems.

* Development Enviroments
    + [vim](https://www.vim.org): Very fast & reliable. High learning curve.
    + [vscode](https://code.visualstudio.com): General Purpose IDE for all sort of languages. Tons of plugins.
    + [PyCharm](https://www.jetbrains.com/pycharm/): Ecspecially useful for coding in Python.
    + [RStudio](https://rstudio.com): The working enviroment for R.
    + [Overleaf](https://www.overleaf.com): Collaborative Latex Editor.
* Command Line 
    + [Kitty](https://sw.kovidgoyal.net/kitty/invocation/): My terminal emulator of choice. 
    + [iTerm](https://iterm2.com): Only tool on the list which is only available for MacOS. Has some really nice plugins.
    + [oh-my-zsh](https://ohmyz.sh): Many different extension possibilities and fun plugins available.
    + [how2](https://github.com/santinic/how2): stackoverflow from the terminal. 
    + [bat](https://github.com/sharkdp/bat): "better" version of cat.

* Different files
    + [vimrc](files/vimrc.txt): My current vimrcm, which is constantly changing. As a package manager I use [vundle](https://github.com/VundleVim/Vundle.vim).
    + [zshrc](files/zshrc.txt): Current zshrc, which is also changing constantly. 
    

